default:
  image: "rust:latest" 

stages:
  - check
  - lint
  - test
  - doc
  - build

format:
  stage: check
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt -- --check

license:
  stage: check
  script:
    - ./utils/license-check.sh

lint -F reqwest_async:
  stage: lint
  needs: ["format", "license"]
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -F reqwest_async -- -D warnings

lint -F reqwest_blocking:
  stage: lint
  needs: ["format", "license"]
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -F reqwest_blocking -- -D warnings

lint -F ureq_blocking:
  stage: lint
  needs: ["format", "license"]
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -F ureq_blocking -- -D warnings

test -F reqwest_async:
  stage: test
  needs: ["lint -F reqwest_async"]
  script:
    - cargo test -F reqwest_async --verbose

test -F reqwest_blocking:
  stage: test
  needs: ["lint -F reqwest_blocking"]
  script:
    - cargo test -F reqwest_blocking --verbose

test -F ureq_blocking:
  stage: test
  needs: ["lint -F ureq_blocking"]
  script:
    - cargo test -F ureq_blocking --verbose

doc -F reqwest_async:
  stage: doc
  needs: ["lint -F reqwest_async"]
  script:
    - cargo doc -F reqwest_async --workspace --no-deps

doc -F reqwest_blocking:
  stage: doc
  needs: ["lint -F reqwest_blocking"]
  script:
    - cargo doc -F reqwest_blocking --workspace --no-deps

doc -F ureq_blocking:
  stage: doc
  needs: ["lint -F ureq_blocking"]
  script:
    - cargo doc -F ureq_blocking --workspace --no-deps

build -F reqwest_async:
  stage: build
  needs: ["test -F reqwest_async", "doc -F reqwest_async"]
  script:
    - cargo build -F reqwest_async

build -F reqwest_blocking:
  stage: build
  needs: ["test -F reqwest_blocking", "doc -F reqwest_blocking"]
  script:
    - cargo build -F reqwest_blocking

build -F ureq_blocking:
  stage: build
  needs: ["test -F ureq_blocking", "doc -F ureq_blocking"]
  script:
    - cargo build -F ureq_blocking
